mode: "sbs"
model_dir: "YOUR TRAINED MODEL"
swap_space: 24
temperature: 0.5
max_depth: 15
max_tokens: 512
prompt_wrap: "react_sft" 
result_unwrap: "react_sft"
step_delim: "\n"
stop: ["</step>","</step>\n","</step>\n\n","</step>\n\n\n"]
seed: 42
need_value_func: True
step_beam_width: 3      # B1
n_generate_sample: 4    # B2
best_of: 5
remove_duplicate: True
verbose: False